from sage.all import PolynomialRing, ZZ

pr = PolynomialRing(ZZ, ('c', 'd', 'X1', 'X2', 'Y1', 'Y2'), 6)
c, d, X1, X2, Y1, Y2 = pr.gens()
ccd = c * c * d
ccd2 = 2 * c * c * d
c2 = 2 * c
cc4 = 4 * c * c
k = 1 / c
Z1, Z2 = 1, 1
formula = {}
A = X1 * Z2
formula['A'] = A
B = Y1 * Z2
formula['B'] = B
C = Z1 * X2
formula['C'] = C
D = Z1 * Y2
formula['D'] = D
E = A * B
formula['E'] = E
F = C * D
formula['F'] = F
G = E + F
formula['G'] = G
H = E - F
formula['H'] = H
t0 = A + D
formula['t0'] = t0
t1 = B + C
formula['t1'] = t1
t2 = t0 * t1
formula['t2'] = t2
t3 = t2 - G
formula['t3'] = t3
X3 = t3 * H
formula['X3'] = X3
t4 = A - C
formula['t4'] = t4
t5 = B + D
formula['t5'] = t5
t6 = t4 * t5
formula['t6'] = t6
t7 = t6 - H
formula['t7'] = t7
Y3 = t7 * G
formula['Y3'] = Y3
t8 = G * H
formula['t8'] = t8
Z3 = c * t8
formula['Z3'] = Z3
