from sage.all import PolynomialRing, ZZ

pr = PolynomialRing(ZZ, ('c', 'd', 'X1', 'X2', 'Y1', 'Y2'), 6)
c, d, X1, X2, Y1, Y2 = pr.gens()
ccd = c * c * d
ccd2 = 2 * c * c * d
c2 = 2 * c
cc4 = 4 * c * c
k = 1 / c
Z1, Z2 = 1, 1
formula = {}
iX2 = i * X2
formula['iX2'] = iX2
C2 = Y2 + iX2
formula['C2'] = C2
D2 = Y2 - iX2
formula['D2'] = D2
iX1 = i * X1
formula['iX1'] = iX1
C1 = Y1 + iX1
formula['C1'] = C1
D1 = Y1 - iX1
formula['D1'] = D1
A = Z1 * Z2
formula['A'] = A
t0 = A ** 2
formula['t0'] = t0
B = 2 * t0
formula['B'] = B
C = C1 * C2
formula['C'] = C
D = D1 * D2
formula['D'] = D
L = D + C
formula['L'] = L
M = Y1 * Y2
formula['M'] = M
t1 = 2 * M
formula['t1'] = t1
N = t1 - L
formula['N'] = N
t2 = M * N
formula['t2'] = t2
E = d * t2
formula['E'] = E
F = B - E
formula['F'] = F
G = B + E
formula['G'] = G
t3 = D - C
formula['t3'] = t3
t4 = F * t3
formula['t4'] = t4
t5 = A * t4
formula['t5'] = t5
X3 = i * t5
formula['X3'] = X3
t6 = G * L
formula['t6'] = t6
Y3 = A * t6
formula['Y3'] = Y3
t7 = G * F
formula['t7'] = t7
Z3 = c * t7
formula['Z3'] = Z3
