#!/usr/bin/env python3
import argparse
import json
import sys
from pathlib import Path

from dissect.definitions import TRAIT_PATH, TRAIT_MODULE_PATH, TRAIT_NAMES
from dissect.traits.example_curves import curves
from dissect.utils.json_handler import save_into_json, load_from_json


def load_params_local(local_params):
    if local_params:
        print("Input parameters: ")
    params = []
    for param_name in local_params:
        try:
            param_value = json.loads(input(param_name + ": "))
        except json.decoder.JSONDecodeError:
            print("Invalid format")
            return False
        params.append(param_value)
    return params



def create_unittest(name):
    results = load_from_json(Path(TRAIT_PATH, name, name + "_structure.json"))
    if Path(TRAIT_PATH, "../unit_tests", "test_" + name + ".py").is_file():
        answer = input("Unittest for " + name + " already exists, overwrite? [Y/n]")
        if answer in ["n", "N"]:
            return
    f = open(Path(TRAIT_PATH, "../unit_tests", "test_" + name + ".py"), "w")
    to_write = ""
    to_write += "import unittest, ast\n"
    to_write += (
        "from dissect.traits."
        + name
        + "."
        + name
        + " import "
        + name
        + "_curve_function\n"
    )
    to_write += "from dissect.traits.example_curves import curve_names\n"
    to_write += "results=" + str(results) + "\n"
    to_write += (
        "\nclass Test" + name[0].upper() + name[1:] + "(unittest.TestCase):\n \n"
    )
    for curve in results.keys():
        to_write += "    def test_auto_generated_" + str(curve) + "(self):\n"
        to_write += '        """This test has been auto-generated by gen_unittest""" \n'
        to_write += (
            '        params = ast.literal_eval(list(results["'
            + str(curve)
            + '"].keys())[0]).values()\n'
        )
        to_write += (
            "        computed_result = "
            + name
            + '_curve_function(curve_names["'
            + str(curve)
            + '"],*params)\n'
        )
        to_write += (
            '        self.assertEqual(list(results["'
            + str(curve)
            + '"].values())[0],computed_result)\n\n'
        )
    to_write += "\nif __name__ == '__main__':\n"
    to_write += "   unittest.main()\n"
    to_write += '   print("Everything passed")\n'
    f.write(to_write)
    f.close()



def main(trait_name=None, u=False, s=False):
    if trait_name == None:
        parser = argparse.ArgumentParser(
            description="Create unit tests"
        )
        
        requiredNamed = parser.add_argument_group("required named arguments")
        requiredNamed.add_argument(
            "-n",
            "--trait_name",
            metavar="trait_name",
            type=str,
            action="store",
            help="List names of the traits seperated by comma or all; available traits: "
            + ", ".join(TRAIT_NAMES),
            required=True,
        )

        args = parser.parse_args()
        trait_name = args.trait_name

    if trait_name == "all":
        trait_name = TRAIT_NAMES
    else:
        trait_name = [n.strip() for n in trait_name.split(",")]
    for name in trait_name:
        create_unittest(name)


if __name__ == "__main__":
    main()
