import ast, sys, os
from curve_analyzer.utils.json_handler import save_into_json, load_from_json
from curve_analyzer.definitions import TEST_PATH, TEST_MODULE_PATH, TEST_prefixes
from curve_analyzer.tests.testing_curves import curves



def create_structure_file(name):
    f = open(TEST_PATH+"/"+name+"/"+name+".params","r")
    params = ast.literal_eval(f.read())
    f.close()
    local_params = params["params_local_names"]
    if local_params:
        print("Input parameters: ")
    params = []
    for param_name in local_params:
        params.append(int(input(param_name+": ")))
    module_name = TEST_MODULE_PATH+'.'+name + '.' + name
    __import__(module_name)
    curve_function = getattr(sys.modules[module_name], name+"_curve_function")
    params_local = str(dict(zip(local_params, params)))
    result = {}
    for curve in curves:
        print("Curve "+curve.name+": ")
        result[curve.name] = {}
        computed_result = curve_function(curve, *params)
        for key in computed_result.keys():
            key_result = input("Result for "+key+": ")
            if str(computed_result[key])!=key_result:
                print("Wrong result, should be: " + str(computed_result[key]))
                return False
        result[curve.name][params_local] = computed_result
    json_file = TEST_PATH+"/"+ name+"/" +name +'_structure.json'
    save_into_json(result, json_file, mode='w')
    return True

def create_unittest(name):
    results = load_from_json(TEST_PATH+"/"+name+"/"+name+"_structure.json")
    if os.path.exists(TEST_PATH+"/unit_tests/test_"+name+".py"):
        answer = input("Unittest for "+name+" already exists, overwrite? [Y/n]")
        if answer in "[n,N]":
            return
    f = open(TEST_PATH+"/unit_tests/test_"+name+".py","w")
    f.write("import unittest, ast\n")
    f.write("from curve_analyzer.tests."+name+"."+name+" import "+name+"_curve_function\n")
    f.write("from curve_analyzer.tests.testing_curves import curves, curve_names\n")
    f.write("results="+str(results)+"\n")
    f.write("\nclass Test_"+name+"(unittest.TestCase):\n \n")
    for curve in results.keys():
        f.write("    # This test has been auto-generated by gen_unittest\n")
        f.write("    def test_auto_generated_"+str(curve)+"(self):\n")
        f.write("        params = ast.literal_eval(list(results[\""+str(curve)+"\"].keys())[0]).values()\n")
        f.write("        computed_result = "+name+"_curve_function(curve_names[\""+str(curve)+"\"],*params)\n")
        f.write("        self.assertEqual(computed_result,list(results[\""+str(curve)+"\"].values())[0])\n\n")
    f.write("\nif __name__ == '__main__':\n")
    f.write("   unittest.main()\n")
    f.write("   print(\"Everything passed\")\n")
    f.close()

tests_to_skip = ['a08']

def main():
    name = input("Name of the test (type \'all\' for all tests): ")
    if name!="all":
        if create_structure_file(name):
            create_unittest(name)
    else:
        directory = TEST_PATH
        for filename in os.listdir(directory):
            if filename in tests_to_skip:
                continue
            if not filename[0] in TEST_prefixes:
                continue
            try:
                int(filename[1:], 10)
            except:
                continue
            if create_structure_file(filename):
                create_unittest(filename)



main()




