import unittest, ast
from dissect.traits.i11.i11 import i11_curve_function
from dissect.traits.example_curves import curves, curve_names
results={'secp112r2': {"{'formula_file': 'shortw/projective/addition/add-1998-cmo-2.op3'}": {'points': [[0, 383296273550222982847666203456013], [3610075134545239076002374364665933, 0]], 'len': 2}}, 'bn158': {"{'formula_file': 'shortw/projective/addition/add-1998-cmo-2.op3'}": {'points': [], 'len': 0}}, 'brainpoolP160r1': {"{'formula_file': 'shortw/projective/addition/add-1998-cmo-2.op3'}": {'points': [], 'len': 0}}}

class TestI11(unittest.TestCase):
 
    def test_auto_generated_secp112r2(self):
        """This test has been auto-generated by gen_unittest""" 
        params = ast.literal_eval(list(results["secp112r2"].keys())[0]).values()
        computed_result = i11_curve_function(curve_names["secp112r2"],*params)
        self.assertEqual(computed_result,list(results["secp112r2"].values())[0])

    def test_auto_generated_bn158(self):
        """This test has been auto-generated by gen_unittest""" 
        params = ast.literal_eval(list(results["bn158"].keys())[0]).values()
        computed_result = i11_curve_function(curve_names["bn158"],*params)
        self.assertEqual(computed_result,list(results["bn158"].values())[0])

    def test_auto_generated_brainpoolP160r1(self):
        """This test has been auto-generated by gen_unittest""" 
        params = ast.literal_eval(list(results["brainpoolP160r1"].keys())[0]).values()
        computed_result = i11_curve_function(curve_names["brainpoolP160r1"],*params)
        self.assertEqual(computed_result,list(results["brainpoolP160r1"].values())[0])


if __name__ == '__main__':
   unittest.main()
   print("Everything passed")
