name: ci

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Determine Docker tag
        id: determine_tag
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/v')
        run: echo "tag=$(echo ${{ github.ref }} | sed -e 's|refs/tags/v||')" >> $GITHUB_OUTPUT
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: crocsmuni/dissect:${{ steps.determine_tag.outputs.tag || 'latest' }}